name: Desktop builds

on:
  push:

  workflow_dispatch:
    inputs:
      downloadPublicVersion:
        description: 'public version # to test against'
      apis:
          description: 'CSV of apis whose quickstart examples we should build'
          default: 'admob,analytics,auth,database,dynamic_links,firestore,functions,messaging,remote_config,storage'
          required: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.architecture }}-${{ matrix.msvc_runtime}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        build_type: ["Release", "Debug"]
        architecture: ["x64", "x86"]
        msvc_runtime: ["static", "dynamic"]
        python_version: [3.7]

        include:
        - os: windows-latest
          vcpkg_triplet_suffix: "windows-static"
        - os: windows-latest
          msvc_runtime: "dynamic"
          vcpkg_triplet_suffix: "windows-static-md"
        - os: ubuntu-latest
          vcpkg_triplet_suffix: "linux"
        - os: macos-latest
          vcpkg_triplet_suffix: "osx"

        exclude:
        - os: macos-latest
          architecture: "x86"
        - os: macos-latest
          msvc_runtime: "dynamic"
        - os: ubuntu-latest
          msvc_runtime: "dynamic"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/checkout@v2
        with:
          repository: 'firebase/firebase-cpp-sdk'
          ref : 'dev'
          submodules: true
          path: 'firebase-cpp-sdk-source'

      - name: download public SDK package from web
        if: ${{ github.event.inputs.downloadPublicVersion != '' }}
        shell: bash
        run: |
          if [[ ! "${{ github.event.inputs.downloadPublicVersion }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo Invalid version number: "${{ github.event.inputs.downloadPublicVersion }}"
            exit 1
          fi
          set +e
          # Retry up to 10 times because Curl has a tendency to timeout on
          # Github runners.
          for retry in {1..10} error; do
          if [[ $retry == "error" ]]; then exit 5; fi
            curl -L https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_${{ github.event.inputs.downloadPublicVersion }}.zip --output firebase_cpp_sdk.zip && break
            sleep 300
          done
          set -e

      - name: Unzip Firebase C++ SDK
        shell: bash
        if: ${{ github.event.inputs.downloadPublicVersion != '' }}
        run: |
          ls
          if [ "$RUNNER_OS" == "Windows" ]; then
            7z x firebase_cpp_sdk.zip
          else
            unzip -q firebase_cpp_sdk.zip
          fi

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: 'x64'

      - name: Build apps against Firebase C++ source
        shell: bash
        if: ${{ github.event.inputs.downloadPublicVersion == '' }}
        env:
          APIS: ${{ github.event.inputs.apis}}
        run: |
          OLDIFS=$IFS
          IFS=','
          set -f
          apilist="${APIS:-auth,messaging}"
          for api in $apilist; do
            set +f
            echo "$api"
            python firebase-cpp-sdk-source/scripts/build_desktop_app_with_firebase.py --sdk_dir firebase-cpp-sdk-source --app_dir $api/testapp --build_dir build --msvc_runtime_library ${{ matrix.msvc_runtime }}
          done
          set +f
          IFS=$OLDIFS

      - name: Build apps against Firebase C++ prebuilt libraries
        shell: bash
        if: ${{ github.event.inputs.downloadPublicVersion != '' }}
        env:
          APIS: ${{ github.event.inputs.apis}}
        run: |
          OLDIFS=$IFS
          IFS=','
          set -f
          apilist="${APIS:-auth,messaging}"
          for api in $apilist; do
            set +f
            echo "$api"
            python firebase-cpp-sdk-source/scripts/build_desktop_app_with_firebase.py --sdk_dir firebase_cpp_sdk --app_dir $api/testapp --build_dir build --msvc_runtime_library ${{ matrix.msvc_runtime }}
          done
          set +f
          IFS=$OLDIFS

      - name: Print built libraries
        shell: bash
        env:
          APIS: ${{ github.event.inputs.apis}}
        run: |
          OLDIFS=$IFS
          IFS=','
          set -f
          apilist="${APIS:-auth,messaging}"
          for api in $apilist; do
            set +f
            find $api/testapp/build -name "*.lib"
            find $api/testapp/build -name "*.dll"
            find $api/testapp/build -name "*.dylib"
            find $api/testapp/build -name "*.a"
            find $api/testapp/build -name "*.so"
            find $api/testapp/build -name "*.framework"
            find $api/testapp/build -name "desktop_testapp*"
          done
          set +f
          IFS=$OLDIFS

      - name: Inspect firebase libraries for cpu arch and msvc runtime.
        shell: bash
        env:
          APIS: ${{ github.event.inputs.apis}}
        run: |
          OLDIFS=$IFS
          IFS=','
          set -f
          apilist="${APIS:-auth,messaging}"
          for api in $apilist; do
            set +f
            python firebase-cpp-sdk-source/scripts/gha/inspect_built_libraries.py $api/testapp/build
          done
          set +f
          IFS=$OLDIF
        continue-on-error: true
